version: '1'

services:
  postgres:
    image: 'postgres:11.1'
    domainname: market
    ports:
      - "5434:5432"
#      # -- проброс порта наверх "Пароль снаружи:пароль внутри"
#      # -- environment - не общая для всех контейнеров переменная. Переменные среды отличаются т.е. в другом образе они могут быть иными
#    #Эти переменные придумывают создатели образов для доккера. В документации должно быть описание всех возможных настроек
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
#    # -- Здесь тестируем подключение
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres"]
      interval: 5s
      timeout: 1s
      retries: 2

  flyway:
    image: 'boxfuse/flyway'
    command: -url=jdbc:postgresql://postgres:5432/postgres -schemas=public -user=postgres -password=postgres -connectRetries=30 migrate
    # -- volumes - это маппинг локального источника данных flyway с источником в доккере
    # -- в примере к уроку инит файлы лежали в корне проекта в папке flyway (- ./flyway:/flyway/sql) у меня же лежит в service core
    volumes:
      - ./service-core/src/main/resources/db/migration:/flyway/sql
    # -- Указали зависимость одного контейнера от другоги. Важно для корректной псследовательности раскатки при запуске
    depends_on:
      - postgres

#  flyway2:
#    image: boxfuse/flyway
#    command: -url=jdbc:postgresql://postgres:5432/postgres -schemas=public -user=postgres -password=postgres -connectRetries=30 migrate
#    # -- volumes - это маппинг локального источника данных flyway с источником в доккере
#    # -- в примере к уроку инит файлы лежали в корне проекта в папке flyway (- ./flyway:/flyway/sql) у меня же лежит в service core
#    volumes:
#      - ./auth-service/src/main/resources/db/migration:/flyway/sql
#    # -- Указали зависимость одного контейнера от другоги. Важно для корректной псследовательности раскатки при запуске
#    depends_on:
#      - postgres


  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
