server:
  port: 5555

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8080"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: http://localhost:8082
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-core
            - JwtAuthFilter
        - id: cart-service
          uri: http://localhost:8081
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-cart
            - JwtAuthFilter
        - id: auth-service
          uri: http://localhost:8083
          predicates:
            - Path=/authentication/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-auth
            - JwtAuthFilter

jwt:
  secret: h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g34g

    #???????????? ???? ??????????? CrossOrigin. ????? ????????? ? ????? ??????? ?????? ????? ????????? ??????? ? ??????? ???? ???? ????????
    #GET POST ? ?.?. ?????? ???????? ????? ??????, ??????? ????? ????????? ? GW.
  #????? ????????? ????? ?????? ???????, ? ????? ??????
    #???? ???-?? ?????????? ?? ????? http://localhost:5555/core/api/v1/ GW ???????????? ?????? ?? http://localhost:8189/market-core/api/v1
     #              StripPrefix=1 ????????? ??????? ????? ?????? ???????? ????? /xxx/ ????? ?? ?????????? ?? ??????. ? ??????? ???? ???????? /core/
    #              PrefixPath=/market-core - ????????? ? http:// localhost:8189 ??????????????? URL ????????? ????? = ????,
  #              JwtAuthFilter ????????? ?????? ????? ?????? ??????, ??????? ????? ??????????? ? headers ? username ? ??????, ??????? ?????????? ? ?????????????? URL

#logging:
#  level:
#    reactor:
#      netty: TRACE
#    org:
#      springframework:
#        cloud:
#          gateway: TRACE

