server:
  port: 8082
  servlet:
    context-path: /market-core
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/postgres?currentSchema=public
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
integrations:
  cart-service:
    url: http://localhost:8033/market-cart
    read-timeout: 10000
    write-timeout: 3000
    connect-timeout: 5000



