server:
  port: 8081
  servlet:
    context-path: /market-cart
integrations:
  product-service:
    url: http://localhost:8082/market-core
    read-timeout: 10000
    write-timeout: 3000
    connect-timeout:
cart-service:
  cart-prefix: market_
